# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c8d55ca899fb6f45fcd442cfd854a2961911eaf2d8bb275d4e89e0d2793e7d88cfa25a091e97962893fe50b1a9a800954b4bf0a9fe38ba1125d2e43f80badcd

test:
  secret_key_base: 5f8a89f0b448c478c212fb26fe30fbcf51eadb2d44b3c689ac3bb65c86f10d6f0c400c28043fe8ee9dc0161e42ceea2dca239af6b9c5a31802a25c347e4e0ed4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
